import { withEnglishAdminOperations } from '../adminOperationsFallback.js';

export default withEnglishAdminOperations({
  settings: { adminOperations: {
    tabs: { capabilities: '功能', credentials: '凭据', runnerPools: '运行器池' },
    agentTemplates: {
      title: '智能体模板', subtitle: '覆盖 Agent Studio 创建目录：模板名称、配置类型和说明', addTemplate: '添加模板', empty: '尚未配置覆盖项。Agent Studio 将使用内置默认值。', startFromNew: '从头开始（新建自定义模板）', loadFailed: '无法加载智能体模板：{error}', templateKeyRequired: '必须填写模板键', nameRequired: '必须填写名称', saveFailed: '保存失败：{error}', deleteMessage: '确定删除“{name}”的覆盖项吗？这将恢复默认模板。', editOverride: '编辑模板覆盖项', addOverride: '添加模板覆盖项', startFromDefault: '从默认模板开始', startFromPlaceholder: '覆盖内置模板或创建新模板', startFromHelp: '选择默认模板会用您的修改覆盖它；“从头开始”会创建全新模板。', builtInOverride: '此覆盖项将替换内置模板“{name}”。', namePlaceholder: '例如：软件工程师', instructionsPlaceholder: '此模板的系统提示词或角色设定',
    },
    llmConnections: {
      title: 'AI 连接', subtitle: '配置用于智能功能的 AI 模型提供商', addConnection: '添加连接', empty: '尚未配置 AI 连接。', addFirst: '添加第一个连接', referenced: '已被启用的功能引用', visionTitle: '此模型可以分析工作项中的图片', noVisionTitle: '此模型仅处理文本，无法查看图片', addTitle: '添加 AI 连接', editTitle: '编辑 AI 连接', disableWarning: '禁用此连接会使依赖它的 LLM 操作功能在运行时失效。', disableWarningHelp: '引用方：{capabilities}。这些功能仍显示为已启用，但会持续失败，直到重新启用连接或改用其他连接。', namePlaceholder: '例如：OpenRouter Claude Sonnet', selectProvider: '选择提供商…', keyConfigured: '密钥已配置（留空可保留）', enterApiKey: '输入 API 密钥', searchModels: '搜索模型或输入 ID…', typeModelId: '输入模型 ID 或点击刷新', supportsImages: '支持图片输入', lastAttemptFailed: '上次尝试失败：{error}', enterBaseUrlHelp: '输入基础 URL 以获取模型，或直接手动输入模型 ID。', noCachedModels: '没有缓存模型。点击刷新从 {provider} 获取，或手动输入模型 ID。', selectModel: '选择模型…', providerConfig: '提供商配置（JSON）', providerConfigHelp: '可选的顶层字段会合并到提供商请求中。Windshift 的现有字段优先。', visionAuto: '自动（根据模型检测）', visionOn: '开启（强制图片模式）', visionOff: '关闭（强制纯文本）', visionHelp: '控制编码智能体能否向模型发送图片。自动模式使用已知模型能力；本地或自定义模型可手动覆盖。', rateHint: '每 100 万令牌 {prompt}/{completion}', refreshedNow: '刚刚刷新', refreshedMinutes: '{count} 分钟前刷新', refreshedHours: '{count} 小时前刷新', refreshedDays: '{count} 天前刷新', modelsFetched: '已从 {provider} 获取 {count} 个模型', refreshFailed: '无法刷新模型', loadFailed: '无法加载 AI 连接', oneCapability: '1 个已启用操作功能：{name}', manyCapabilities: '{count} 个已启用操作功能：{names}', deleteTitle: '删除 AI 连接', deleteMessage: '确定删除 {name} 吗？此操作无法撤销。', deleteImpact: '此连接被 {capabilities} 引用。相关功能将停止工作。', deleted: 'AI 连接已删除', deleteFailed: '无法删除连接', configObject: '提供商配置必须是 JSON 对象', configJson: '提供商配置必须是有效的 JSON', created: 'AI 连接已创建', createFailed: '无法创建连接', updated: 'AI 连接已更新', updateFailed: '无法更新连接', testPassed: '连接测试通过', testFailed: '连接测试失败',
    },
    actionCapabilities: { availableAll: '所有工作区均可用', availableAllHelp: '任何工作区的操作都可以引用此功能。', restrict: '限制到指定工作区', restrictHelp: '只有下方选择的工作区可以引用此功能。', noWorkspaces: '没有可用的工作区。', useCredential: '使用身份验证凭据', globalCredentialHelp: '全局功能只能引用全局凭据。', workspaceCredentialHelp: '工作区功能可以引用全局凭据或已为其工作区授权的凭据。', scheme: '方案（仅 Bearer 令牌）', additionalHeaders: '其他机密请求头', addSecretHeader: '添加机密请求头', additionalHeadersHelp: '适用于需要多个机密请求头的 API。每一行都会在请求时解析凭据。', defaultHeadersHelp: '仅限非机密请求头。身份验证令牌应在下方配置。' },
    actionCredentials: { title: '操作凭据', subtitle: '供 HTTP 功能引用的加密 API 令牌。机密值只能写入，保存后无法读回。', add: '添加凭据', addFirst: '添加第一个凭据', empty: '尚无凭据。', basicAuth: '基本认证（用户名:密码）', customHeader: '自定义请求头值', loadFailed: '无法加载操作凭据', nameSecretRequired: '名称和机密值均为必填项', workspaceRequired: '请至少选择一个工作区，或允许所有工作区使用。', created: '凭据已创建（{prefix}）', createFailed: '无法创建凭据', updateFailed: '无法更新凭据', rotated: '机密值已替换（{prefix}）', rotateFailed: '无法替换机密值', deleteMessage: '删除 {name}？仍引用它的功能将在运行时失败。', deleteFailed: '无法删除凭据', storedSecret: '已存储，绝不会完整显示', availableAll: '所有工作区均可用', availableAllHelp: '任何工作区都可以使用此凭据。', restrict: '限制到指定工作区', restrictHelp: '只有下方选择的工作区可以使用此凭据。', noWorkspaces: '没有可用的工作区。', secretPlaceholder: '输入令牌、API 密钥或用户名:密码', secretHelp: '以加密方式存储，不会再次显示；需要时可替换。', metadata: '元数据（JSON，可选）', metadataHelp: '仅限非机密元数据。token、secret、password 等键会被拒绝。', storedRotate: '已存储（{prefix}）— 使用“替换”设置新值。', rotateTitle: '替换机密值 — {name}', rotateHelp: '输入新的机密值。旧值会立即被替换且无法恢复。' },
    runnerPools: { title: '运行器池', subtitle: '执行编码智能体任务的远程运行器池。创建注册令牌即可添加运行器主机。', empty: '没有运行器池', emptyDescription: '先创建池，再创建注册令牌以连接运行器主机。', registrationTokens: '注册令牌 — {name}', noTokens: '尚无令牌', runnersForPool: '运行器 — {name}', noRunners: '尚未注册运行器', newPoolTitle: '新建运行器池', maxConcurrentRuns: '最大并发运行数', zeroUnlimited: '0 = 无限制', availableAll: '所有工作区均可用', mintTitle: '创建注册令牌', expiresHours: '有效期（小时）', zeroNeverExpires: '0 = 永不过期（撤销后停用）', addHostTitle: '添加运行器主机', installHelp: '在运行器主机上执行此命令。它会使用服务器 URL、匹配的镜像标签和新令牌安装并启动运行器容器。', manualPrefix: '改为手动设置？将令牌设为', setTokenPrefix: '将令牌设为', tokenOnce: '并配置到运行器主机。令牌仅显示一次，之后无法再次获取。', loadFailed: '无法加载运行器池', tokensLoadFailed: '无法加载令牌', runnersLoadFailed: '无法加载运行器实例', created: '运行器池已创建', createFailed: '无法创建运行器池', mintFailed: '无法创建令牌', revokeTokenTitle: '撤销注册令牌', revokeTokenMessage: '撤销令牌 {prefix}…？运行器将无法再用它注册。', revokeTokenFailed: '无法撤销令牌', revokeRunnerMessage: '移除运行器 {name}？它必须重新注册才能再次加入。', revokeRunnerFailed: '无法移除运行器', copied: '已复制到剪贴板', copyFailed: '复制失败，请手动选择并复制' },
  } },
  workspaceMembers: {
    invalidWorkspace: '工作区无效。', loadFailed: '无法加载工作区成员。', addMemberFailed: '无法添加成员：{error}', addGroupFailed: '无法添加用户组：{error}',
    removeRoleTitle: '从 {name} 移除“{role}”角色？', removeRoleMessage: '这将移除角色分配及其权限。', removeRoleFailed: '无法移除角色：{error}',
    summaryTitle: '访问摘要', summaryDescription: '显示此工作区中的角色分配。没有分配成员或用户组的角色对所有人开放。权限层级：{viewer} → {editor} → {tester}。',
    role: '角色', effectiveAccess: '访问权限', assignments: '分配对象', memberOrGroup: '成员或用户组', rolesLabel: '角色', actions: '操作',
    roles: {
      viewer: { name: '查看者', description: '查看工作区内容并参与讨论' },
      editor: { name: '编辑者', description: '在此工作区创建和编辑工作项' },
      tester: { name: '测试者', description: '查看工作项、执行测试、管理测试用例并创建缺陷' },
      administrator: { name: '管理员', description: '管理整个工作区，包括访问权限' },
    },
    memberCount: '{count} 名成员', memberCount_one: '{count} 名成员', memberCount_other: '{count} 名成员', everyone: '所有人', noDirectAssignments: '无直接分配',
    addMember: '添加成员', addGroup: '添加用户组', searchPlaceholder: '按姓名或邮箱搜索成员或用户组…', loading: '正在加载成员…', empty: '尚无成员或用户组。请添加成员或用户组以配置此工作区的访问权限。', noSearchResults: '未找到与“{query}”匹配的成员或用户组。',
    unknownUser: '未知用户', group: '用户组', removeRoleAction: '移除角色：{role}', addMemberTitle: '添加工作区成员', user: '用户', selectUser: '选择用户…', selectRole: '选择角色…', addingMember: '正在添加成员…', cancel: '取消', addGroupTitle: '向工作区添加用户组', selectGroup: '选择用户组…', addingGroup: '正在添加用户组…',
  },
  integrations: {
    directions: { outbound: '出站', inbound: '入站', outboundDescription: 'Windshift 主动连接的应用。添加 OAuth 凭据以读取 Notion 或 Confluence 等外部服务的数据。', inboundDescription: '代表用户连接 Windshift 的应用。只需注册一次第三方应用，用户随后通过 OAuth 2.0 和 PKCE 授权。' },
    providers: { loadFailed: '无法加载集成提供商', saveFailed: '无法保存提供商', deleteMessage: '这会删除集成提供商并断开所有用户的连接。', deleteFailed: '无法删除提供商', namePlaceholder: '我的 Notion 集成' },
    oauthClients: { title: 'OAuth 客户端', subtitle: '注册使用 OAuth 2.0 和 PKCE 授权 Windshift 用户并创建用户级 API 令牌的第三方应用。', empty: '尚未注册 OAuth 客户端', emptyDescription: '点击“注册客户端”添加第三方应用。', loadFailed: '无法加载 OAuth 客户端', updated: 'OAuth 客户端已更新', publicCreated: '公共 OAuth 客户端已创建', saveFailed: '无法保存 OAuth 客户端', rotateTitle: '替换“{name}”的机密值？', rotateMessage: '旧机密值会立即失效。现有令牌可继续使用至过期；后续使用旧机密值的令牌交换会失败。', rotateFailed: '无法替换机密值', deleteMessage: '为此客户端签发的所有访问和刷新令牌都会立即撤销。已连接用户需要重新连接。', deleted: 'OAuth 客户端已删除', deleteFailed: '无法删除 OAuth 客户端', scopeHelp: '签发的访问令牌是用户级 Windshift API 令牌。它继承请求用户的权限，并受所选范围限制。', redirectCount: '重定向 URI：{count}', rotateSecret: '替换客户端机密值', editTitle: '编辑 OAuth 客户端', registerTitle: '注册 OAuth 客户端', confidential: '机密客户端（服务器到服务器，有机密值）', public: '公共客户端（仅 PKCE，无机密值）', clientTypeHelp: '机密客户端在服务器端存储 client_secret。公共客户端每次交换令牌都必须使用 PKCE。', redirectHelp: '每行输入一个 URI。授权请求中的 redirect_uri 必须与其中一个完全匹配。', copySecretNow: '立即复制此机密值', secretWarning: '客户端机密值只显示一次。Windshift 仅存储其 bcrypt 哈希，请在关闭前复制；如果丢失，请替换它。' },
  },
  systemCatalog: {
    statuses: { open: '待处理', inProgress: '进行中', done: '已完成' },
    statusCategories: { toDo: '待办', inProgress: '进行中', done: '已完成' },
  },
});
