import { derived, get, writable } from 'svelte/store';
import { api } from '../api.js';
import { confirm } from '../composables/useConfirm.js';
import { QLBuilder } from '../utils/ql.js';
import { completionFieldToFilterField } from '../utils/qlCompletion.js';
import { t } from './i18n.svelte.js';
import { warningToast } from './toasts.svelte.js';
import { workspacesStore } from './workspaces.svelte.js';

/**
 * Factory that creates a fresh work-item search/filter store.
 *
 * Each consumer (Search page, Collection editor, …) instantiates its own
 * store so filter state never leaks between pages. The store owns the full
 * builder/raw-mode state machine, the QL serialization, the API call, the
 * URL round-trip, and the polished raw-mode UX (confirm-then-snapshot,
 * tryParseToBuilder on reset, warning toast for dropped clauses).
 */
export function createWorkItemSearchStore({ allowEmptyQuery = false } = {}) {
  // ===== Filter state =====
  const searchQuery = writable('');
  const selectedWorkspaces = writable([]);
  const selectedStatuses = writable([]);
  const selectedPriorities = writable([]);
  const dynamicFilters = writable([]);

  // ===== QL mode =====
  // Builder mode: qlQuery is derived from the builder fields.
  // Raw mode:    qlQuery echoes rawQlQuery (the textarea source).
  const rawMode = writable(false);
  const rawQlQuery = writable('');
  const qlError = writable(null);

  // ===== Reference data =====
  const workspaces = writable([]);
  const allStatuses = writable([]);
  const allPriorities = writable([]);
  const statusCategories = writable([]);

  // ===== Results =====
  const workItems = writable([]);
  const loadingItems = writable(false);
  const pagination = writable(null);

  // ===== Derived =====
  const autoGeneratedQl = derived(
    [
      selectedWorkspaces,
      selectedStatuses,
      selectedPriorities,
      searchQuery,
      dynamicFilters,
      workspaces,
    ],
    ([$ws, $st, $pr, $q, $df, $wsRef]) =>
      QLBuilder.buildQuery({
        workspaces: $ws.map((id) => $wsRef.find((w) => w.id === id)?.key).filter(Boolean),
        statuses: $st,
        priorities: $pr,
        search: $q,
        dynamicFields: $df,
      })
  );

  const qlQuery = derived([rawMode, rawQlQuery, autoGeneratedQl], ([$raw, $rawQl, $auto]) =>
    $raw ? $rawQl : $auto
  );

  const hasFilters = derived(
    [
      selectedWorkspaces,
      selectedStatuses,
      selectedPriorities,
      searchQuery,
      dynamicFilters,
      rawMode,
      rawQlQuery,
    ],
    ([$ws, $st, $pr, $q, $df, $raw, $rawQl]) => {
      if ($raw) return $rawQl.trim().length > 0;
      const hasDyn = $df.some(
        (f) => f.field && (f.value !== '' || (f.values && f.values.length > 0))
      );
      return $ws.length > 0 || $st.length > 0 || $pr.length > 0 || $q.trim().length > 0 || hasDyn;
    }
  );

  const combined = derived(
    [
      searchQuery,
      selectedWorkspaces,
      selectedStatuses,
      selectedPriorities,
      dynamicFilters,
      rawMode,
      rawQlQuery,
      qlError,
      workspaces,
      allStatuses,
      allPriorities,
      statusCategories,
      workItems,
      loadingItems,
      pagination,
      autoGeneratedQl,
      qlQuery,
      hasFilters,
    ],
    ([
      $searchQuery,
      $selectedWorkspaces,
      $selectedStatuses,
      $selectedPriorities,
      $dynamicFilters,
      $rawMode,
      $rawQlQuery,
      $qlError,
      $workspaces,
      $allStatuses,
      $allPriorities,
      $statusCategories,
      $workItems,
      $loadingItems,
      $pagination,
      $autoGeneratedQl,
      $qlQuery,
      $hasFilters,
    ]) => ({
      searchQuery: $searchQuery,
      selectedWorkspaces: $selectedWorkspaces,
      selectedStatuses: $selectedStatuses,
      selectedPriorities: $selectedPriorities,
      dynamicFilters: $dynamicFilters,
      rawMode: $rawMode,
      rawQlQuery: $rawQlQuery,
      qlError: $qlError,
      workspaces: $workspaces,
      allStatuses: $allStatuses,
      allPriorities: $allPriorities,
      statusCategories: $statusCategories,
      workItems: $workItems,
      loadingItems: $loadingItems,
      pagination: $pagination,
      autoGeneratedQl: $autoGeneratedQl,
      qlQuery: $qlQuery,
      hasFilters: $hasFilters,
    })
  );

  // ===== Reference data loading =====
  async function loadReferenceData() {
    try {
      const [wsData, stData, prData, catData] = await Promise.all([
        workspacesStore.load(),
        api.statuses.getAll(),
        api.priorities.getAll(),
        api.statusCategories.getAll(),
      ]);
      workspaces.set(wsData || []);
      allStatuses.set(
        (stData || []).map((s) => ({ id: s.id, name: s.name || s.key || '', key: s.key }))
      );
      allPriorities.set(
        (prData || [])
          .slice()
          .sort((a, b) => (a.sort_order ?? 0) - (b.sort_order ?? 0))
          .map((p) => ({ id: p.id, name: p.name, color: p.color || null }))
      );
      statusCategories.set(catData || []);
    } catch (err) {
      console.error('Failed to load reference data:', err);
    }
  }

  // ===== Search execution =====
  async function executeSearch({ page = 1, limit = 50 } = {}) {
    const finalQl = get(qlQuery);
    if (!allowEmptyQuery && !finalQl?.trim()) {
      workItems.set([]);
      pagination.set(null);
      qlError.set(null);
      return;
    }
    loadingItems.set(true);
    qlError.set(null);
    try {
      const response = await api.items.getAll({ ql: finalQl, page, limit });
      if (response?.data) {
        workItems.set(response.data);
        pagination.set(response.pagination || null);
      } else {
        workItems.set(response || []);
        pagination.set(null);
      }
    } catch (err) {
      console.error('Search failed:', err);
      qlError.set(err.message || 'Search failed');
      workItems.set([]);
      pagination.set(null);
    } finally {
      loadingItems.set(false);
    }
  }

  // ===== Raw / builder mode transitions =====
  async function enterRawMode() {
    if (get(rawMode)) return;
    const confirmed = await confirm({
      title: t('collections.rawModeConfirmTitle'),
      message: t('collections.rawModeConfirmMessage'),
      confirmText: t('collections.rawModeConfirmAccept'),
      cancelText: t('common.cancel'),
      variant: 'warning',
    });
    if (!confirmed) return;
    // Snapshot the currently-derived QL so the user starts editing from there.
    rawQlQuery.set(get(qlQuery));
    selectedWorkspaces.set([]);
    selectedStatuses.set([]);
    selectedPriorities.set([]);
    searchQuery.set('');
    dynamicFilters.set([]);
    rawMode.set(true);
    qlError.set(null);
  }

  // Parse a CQL string and apply the resulting builder state. Returns the
  // raw parser result so callers can branch on `dropped` / null.
  async function parseQlAndApplyBuilderState(qlString) {
    let customFieldsCatalog = [];
    // Status/priority catalogs let the parser resolve name-based clauses
    // (`status = "Open"`) back to ids. Prefer the already-loaded reference data;
    // fetch on demand if it isn't ready yet so recovery doesn't race load order.
    let statusCatalog = get(allStatuses);
    let priorityCatalog = get(allPriorities);
    try {
      const [catalog, st, pr] = await Promise.all([
        api.queryLanguage.getCatalog(),
        statusCatalog.length ? null : api.statuses.getAll(),
        priorityCatalog.length ? null : api.priorities.getAll(),
      ]);
      customFieldsCatalog = (catalog?.fields || [])
        .filter((field) => /^cfid_\d+$/i.test(field.name))
        .map(completionFieldToFilterField);
      if (st) {
        statusCatalog = (st || []).map((s) => ({ id: s.id, name: s.name || s.key || '' }));
      }
      if (pr) {
        priorityCatalog = (pr || []).map((p) => ({ id: p.id, name: p.name }));
      }
    } catch (err) {
      console.warn('Failed to load reference data for builder recovery:', err);
    }

    const wsList = get(workspaces);
    const parsed = QLBuilder.tryParseToBuilder(qlString, {
      customFields: customFieldsCatalog,
      statuses: statusCatalog,
      priorities: priorityCatalog,
      workspaces: wsList,
    });

    selectedWorkspaces.set(
      parsed
        ? parsed.workspaces
            .map((reference) => wsList.find((w) => w.key === reference || w.name === reference)?.id)
            .filter(Boolean)
        : []
    );
    selectedStatuses.set(parsed ? parsed.statuses : []);
    selectedPriorities.set(parsed ? parsed.priorities : []);
    searchQuery.set(parsed ? parsed.search : '');
    dynamicFilters.set(parsed ? parsed.dynamicFields : []);

    rawQlQuery.set('');
    rawMode.set(false);
    qlError.set(null);

    return parsed;
  }

  async function resetToBuilder() {
    const parsed = await parseQlAndApplyBuilderState(get(rawQlQuery));
    if (parsed?.dropped) {
      warningToast(t('collections.builderRecoveryDropped'));
    }
  }

  // Try to hydrate builder state from a stored QL (no toast, no confirm).
  // Returns true when the QL was fully recovered into builder fields; the
  // caller should fall back to raw mode otherwise so dropped clauses aren't
  // silently lost.
  async function tryHydrateFromQl(qlString) {
    if (!qlString?.trim()) return false;
    const parsed = await parseQlAndApplyBuilderState(qlString);
    if (!parsed || parsed.dropped) {
      // Restore raw mode with the original QL so nothing is lost.
      selectedWorkspaces.set([]);
      selectedStatuses.set([]);
      selectedPriorities.set([]);
      searchQuery.set('');
      dynamicFilters.set([]);
      rawQlQuery.set(qlString);
      rawMode.set(true);
      return false;
    }
    return true;
  }

  // ===== URL round-trip =====
  function syncToURL(extraParams = {}) {
    const url = new URL(window.location.href);
    const keys = ['raw', 'ql', 'workspaces', 'statuses', 'priorities', 'search', 'dynamicFilters'];
    keys.forEach((k) => url.searchParams.delete(k));

    if (get(rawMode)) {
      const rq = get(rawQlQuery);
      if (rq.trim()) url.searchParams.set('raw', rq);
    } else {
      const sw = get(selectedWorkspaces);
      const ss = get(selectedStatuses);
      const sp = get(selectedPriorities);
      const sq = get(searchQuery);
      const df = get(dynamicFilters);

      if (sw.length > 0) url.searchParams.set('workspaces', sw.join(','));
      if (ss.length > 0) url.searchParams.set('statuses', ss.join(','));
      if (sp.length > 0) url.searchParams.set('priorities', sp.join(','));
      if (sq.trim()) url.searchParams.set('search', sq);

      const dfSerializable = df.filter(
        (f) => f.field && (f.value !== '' || (f.values && f.values.length > 0))
      );
      if (dfSerializable.length > 0) {
        url.searchParams.set('dynamicFilters', JSON.stringify(dfSerializable));
      }
    }

    Object.entries(extraParams).forEach(([k, v]) => {
      if (v == null || v === '') url.searchParams.delete(k);
      else url.searchParams.set(k, String(v));
    });

    window.history.pushState({}, '', url);
  }

  function restoreFromURL() {
    const params = new URLSearchParams(window.location.search);

    // A restore can happen more than once while SearchPage stays mounted
    // (browser Back/Forward after syncToURL's pushState). Reset first so a
    // parameter removed by the history entry also disappears from the UI.
    searchQuery.set('');
    selectedWorkspaces.set([]);
    selectedStatuses.set([]);
    selectedPriorities.set([]);
    dynamicFilters.set([]);
    rawQlQuery.set('');
    rawMode.set(false);
    qlError.set(null);

    // Raw mode (`?raw=…` is canonical; `?ql=…` is accepted for backwards compat).
    const rawParam = params.get('raw') ?? params.get('ql');
    if (rawParam) {
      rawQlQuery.set(rawParam);
      rawMode.set(true);
      return;
    }

    const wsParam = params.get('workspaces');
    if (wsParam) {
      const ids = wsParam
        .split(',')
        .map((id) => parseInt(id, 10))
        .filter((id) => !Number.isNaN(id));
      selectedWorkspaces.set(ids);
    }

    const stParam = params.get('statuses');
    if (stParam) {
      const ids = stParam
        .split(',')
        .map((value) => {
          const parsedId = parseInt(value, 10);
          if (!Number.isNaN(parsedId)) return parsedId;
          const match = get(allStatuses).find(
            (s) => (s.name || s.key || '').toLowerCase() === value.toLowerCase()
          );
          return match ? match.id : null;
        })
        .filter((id) => id !== null && id !== undefined);
      selectedStatuses.set(ids);
    }

    const prParam = params.get('priorities');
    if (prParam) {
      const ids = prParam
        .split(',')
        .map((value) => {
          const parsedId = parseInt(value, 10);
          if (!Number.isNaN(parsedId)) return parsedId;
          const match = get(allPriorities).find(
            (p) => p.name?.toLowerCase() === value.toLowerCase()
          );
          return match ? match.id : null;
        })
        .filter((id) => id !== null && id !== undefined);
      selectedPriorities.set(ids);
    }

    const sqParam = params.get('search');
    if (sqParam) searchQuery.set(sqParam);

    const dfParam = params.get('dynamicFilters');
    if (dfParam) {
      try {
        dynamicFilters.set(JSON.parse(dfParam));
      } catch (err) {
        console.error('Failed to parse dynamic filters from URL:', err);
      }
    }
  }

  return {
    subscribe: combined.subscribe,

    // ===== Filter setters =====
    setSearchQuery: (q) => searchQuery.set(q),
    setSelectedWorkspaces: (ids) => selectedWorkspaces.set(ids),
    setSelectedStatuses: (ids) => selectedStatuses.set(ids),
    setSelectedPriorities: (ids) => selectedPriorities.set(ids),
    setDynamicFilters: (filters) => dynamicFilters.set(filters),

    addDynamicFilter() {
      dynamicFilters.update((current) => [
        ...current,
        { field: null, operator: '=', value: '', values: [] },
      ]);
    },
    updateDynamicFilter(index, filter) {
      dynamicFilters.update((current) => {
        const next = [...current];
        next[index] = filter;
        return next;
      });
    },
    removeDynamicFilter(index) {
      dynamicFilters.update((current) => current.filter((_, i) => i !== index));
    },

    // ===== Raw mode =====
    setRawQlQuery: (q) => rawQlQuery.set(q),
    setQlError: (msg) => qlError.set(msg),
    enterRawMode,
    resetToBuilder,
    tryHydrateFromQl,

    // ===== Hydration helpers (used by Collections.svelte to load a saved collection) =====
    hydrate({
      workspaces: ws = [],
      statuses: st = [],
      priorities: pr = [],
      search = '',
      dynamicFields = [],
      rawQl = null,
    } = {}) {
      // Reset everything first so a hydrate is idempotent.
      selectedWorkspaces.set([]);
      selectedStatuses.set([]);
      selectedPriorities.set([]);
      searchQuery.set('');
      dynamicFilters.set([]);
      rawQlQuery.set('');

      if (rawQl != null) {
        rawQlQuery.set(rawQl);
        rawMode.set(true);
        return;
      }
      selectedWorkspaces.set(ws);
      selectedStatuses.set(st);
      selectedPriorities.set(pr);
      searchQuery.set(search);
      dynamicFilters.set(dynamicFields);
      rawMode.set(false);
    },

    // ===== Reference data =====
    loadReferenceData,
    setWorkspaces: (data) => workspaces.set(data || []),

    // ===== Search =====
    executeSearch,

    // ===== URL =====
    syncToURL,
    restoreFromURL,

    // ===== Clear =====
    clearFilters() {
      searchQuery.set('');
      selectedWorkspaces.set([]);
      selectedStatuses.set([]);
      selectedPriorities.set([]);
      dynamicFilters.set([]);
      rawQlQuery.set('');
      rawMode.set(false);
      qlError.set(null);
    },
  };
}
