import { withEnglishAdminOperations } from '../adminOperationsFallback.js';

export default withEnglishAdminOperations({
  settings: { adminOperations: {
    tabs: { capabilities: 'Capacidades', credentials: 'Credenciales', runnerPools: 'Grupos de ejecutores' },
    agentTemplates: {
      title: 'Plantillas de agentes', subtitle: 'Sobrescribe el catálogo de Agent Studio: nombres de plantillas, tipos de perfil e instrucciones', addTemplate: 'Añadir plantilla',
      empty: 'Aún no hay sobrescrituras. Agent Studio usa los valores predeterminados integrados.', startFromNew: 'Empezar de cero (plantilla nueva)', loadFailed: 'No se pudieron cargar las plantillas de agentes: {error}', templateKeyRequired: 'La clave de la plantilla es obligatoria', nameRequired: 'El nombre es obligatorio', saveFailed: 'No se pudo guardar: {error}',
      deleteMessage: '¿Eliminar la sobrescritura de «{name}»? Se restaurará la plantilla predeterminada.', editOverride: 'Editar sobrescritura de plantilla', addOverride: 'Añadir sobrescritura de plantilla', startFromDefault: 'Partir de un valor predeterminado', startFromPlaceholder: 'Sobrescribe una plantilla integrada o crea una nueva', startFromHelp: 'La plantilla seleccionada se sobrescribirá con tus cambios; «Empezar de cero» crea una plantilla nueva.', builtInOverride: 'Esta sobrescritura reemplaza la plantilla integrada «{name}».', namePlaceholder: 'p. ej., Ingeniero de software', instructionsPlaceholder: 'Instrucción del sistema o función para esta plantilla',
    },
    llmConnections: {
      title: 'Conexiones de IA', subtitle: 'Configura proveedores de modelos de IA para funciones inteligentes', addConnection: 'Añadir conexión', empty: 'Aún no hay conexiones de IA configuradas.', addFirst: 'Añadir la primera conexión', referenced: 'Usada por capacidades activadas', visionTitle: 'Este modelo puede analizar imágenes de los elementos de trabajo', noVisionTitle: 'Este modelo solo procesa texto y no puede ver imágenes',
      addTitle: 'Añadir conexión de IA', editTitle: 'Editar conexión de IA', disableWarning: 'Desactivar esta conexión detendrá las capacidades LLM dependientes durante la ejecución.', disableWarningHelp: 'Usada por {capabilities}. Las capacidades seguirán apareciendo activadas, pero fallarán hasta reactivar o reasignar la conexión.',
      namePlaceholder: 'p. ej., OpenRouter Claude Sonnet', selectProvider: 'Selecciona un proveedor…', keyConfigured: 'Clave configurada (déjala vacía para conservarla)', enterApiKey: 'Introduce la clave de API', searchModels: 'Busca modelos o escribe un ID…', typeModelId: 'Escribe un ID de modelo o pulsa Actualizar', supportsImages: 'Admite entrada de imágenes', lastAttemptFailed: 'El último intento falló: {error}', enterBaseUrlHelp: 'Introduce una URL base para obtener modelos o escribe manualmente el ID del modelo.', noCachedModels: 'No hay modelos en caché. Pulsa Actualizar para obtenerlos de {provider} o escribe un ID manualmente.', selectModel: 'Selecciona un modelo…',
      providerConfig: 'Configuración del proveedor (JSON)', providerConfigHelp: 'Los campos opcionales de nivel superior se combinan con las llamadas al proveedor. Los campos de Windshift tienen prioridad.', visionAuto: 'Automático (detectar del modelo)', visionOn: 'Activado (forzar imágenes)', visionOff: 'Desactivado (forzar solo texto)', visionHelp: 'Controla si el agente de programación puede enviar imágenes al modelo. El modo automático usa la capacidad conocida; puede cambiarse para modelos locales o personalizados.',
      rateHint: '{prompt}/{completion} por 1 M de tokens', refreshedNow: 'Actualizado ahora mismo', refreshedMinutes: 'Actualizado hace {count} min', refreshedHours: 'Actualizado hace {count} h', refreshedDays: 'Actualizado hace {count} d', modelsFetched: 'Se obtuvieron {count} modelos de {provider}', refreshFailed: 'No se pudieron actualizar los modelos', loadFailed: 'No se pudieron cargar las conexiones de IA', oneCapability: '1 capacidad de acción activada: {name}', manyCapabilities: '{count} capacidades de acción activadas: {names}',
      deleteTitle: 'Eliminar conexión de IA', deleteMessage: '¿Eliminar {name}? Esta acción no se puede deshacer.', deleteImpact: 'Esta conexión la usa {capabilities}. Esas capacidades dejarán de funcionar.', deleted: 'Conexión de IA eliminada', deleteFailed: 'No se pudo eliminar la conexión', configObject: 'La configuración del proveedor debe ser un objeto JSON', configJson: 'La configuración del proveedor debe contener JSON válido', created: 'Conexión de IA creada', createFailed: 'No se pudo crear la conexión', updated: 'Conexión de IA actualizada', updateFailed: 'No se pudo actualizar la conexión', testPassed: 'Prueba de conexión superada', testFailed: 'La prueba de conexión falló',
    },
    actionCapabilities: {
      availableAll: 'Disponible en todos los espacios de trabajo', availableAllHelp: 'Las acciones de cualquier espacio pueden usar esta capacidad.', restrict: 'Limitar a espacios de trabajo concretos', restrictHelp: 'Solo los espacios seleccionados abajo pueden usar esta capacidad.', noWorkspaces: 'No hay espacios de trabajo disponibles.', useCredential: 'Usar una credencial de autenticación', globalCredentialHelp: 'Las capacidades globales solo pueden usar credenciales globales.', workspaceCredentialHelp: 'Las capacidades de un espacio pueden usar credenciales globales o autorizadas para ese espacio.', scheme: 'Esquema (solo tokens Bearer)', additionalHeaders: 'Cabeceras secretas adicionales', addSecretHeader: 'Añadir cabecera secreta', additionalHeadersHelp: 'Para API que requieren varias cabeceras secretas. Cada fila resuelve una credencial al ejecutar la solicitud.', defaultHeadersHelp: 'Solo cabeceras no confidenciales. Los tokens de autenticación se indican abajo.',
    },
    actionCredentials: {
      title: 'Credenciales de acciones', subtitle: 'Tokens de API cifrados para capacidades HTTP. Los secretos son de solo escritura y no se pueden leer después de guardarlos.', add: 'Añadir credencial', addFirst: 'Añadir la primera credencial', empty: 'Aún no hay credenciales.', basicAuth: 'Autenticación básica (usuario:contraseña)', customHeader: 'Valor de cabecera personalizada', loadFailed: 'No se pudieron cargar las credenciales de acciones', nameSecretRequired: 'El nombre y el secreto son obligatorios', workspaceRequired: 'Selecciona al menos un espacio o permite todos los espacios de trabajo.',
      created: 'Credencial creada ({prefix})', createFailed: 'No se pudo crear la credencial', updateFailed: 'No se pudo actualizar la credencial', rotated: 'Secreto reemplazado ({prefix})', rotateFailed: 'No se pudo reemplazar el secreto', deleteMessage: '¿Eliminar {name}? Las capacidades que la usen fallarán durante la ejecución.', deleteFailed: 'No se pudo eliminar la credencial', storedSecret: 'Guardado y nunca mostrado por completo', availableAll: 'Disponible en todos los espacios de trabajo', availableAllHelp: 'Cualquier espacio puede usar esta credencial.', restrict: 'Limitar a espacios de trabajo concretos', restrictHelp: 'Solo los espacios seleccionados abajo pueden usar esta credencial.', noWorkspaces: 'No hay espacios de trabajo disponibles.', secretPlaceholder: 'Introduce token, clave de API o usuario:contraseña', secretHelp: 'Se guarda cifrado y no volverá a mostrarse. Puede reemplazarse cuando sea necesario.', metadata: 'Metadatos (JSON, opcional)', metadataHelp: 'Solo metadatos no confidenciales. Se rechazan claves como token, secret y password.', storedRotate: 'Guardado ({prefix}); usa Reemplazar para cambiarlo.', rotateTitle: 'Reemplazar secreto — {name}', rotateHelp: 'Introduce el secreto nuevo. El valor anterior se reemplazará inmediatamente y no podrá recuperarse.',
    },
    runnerPools: {
      title: 'Grupos de ejecutores', subtitle: 'Grupos de ejecutores remotos para trabajos del agente de programación. Crea un token de registro para añadir un host.', empty: 'No hay grupos de ejecutores', emptyDescription: 'Crea un grupo y después un token de registro para conectar un host ejecutor.', registrationTokens: 'Tokens de registro — {name}', noTokens: 'Aún no hay tokens', runnersForPool: 'Ejecutores — {name}', noRunners: 'No hay ejecutores registrados', newPoolTitle: 'Nuevo grupo de ejecutores', maxConcurrentRuns: 'Máximo de ejecuciones simultáneas', zeroUnlimited: '0 = sin límite', availableAll: 'Disponible para todos los espacios', mintTitle: 'Crear token de registro', expiresHours: 'Caduca en (horas)', zeroNeverExpires: '0 = no caduca (revócalo para desactivarlo)', addHostTitle: 'Añadir el host ejecutor',
      installHelp: 'Ejecuta esto en el host. Instala e inicia el contenedor con la URL del servidor, la etiqueta de imagen adecuada y el token nuevo.', manualPrefix: '¿Configuración manual? Define el token como', setTokenPrefix: 'Define el token como', tokenOnce: 'en el host ejecutor. Solo se muestra una vez y no se puede recuperar.', loadFailed: 'No se pudieron cargar los grupos de ejecutores', tokensLoadFailed: 'No se pudieron cargar los tokens', runnersLoadFailed: 'No se pudieron cargar los ejecutores', created: 'Grupo de ejecutores creado', createFailed: 'No se pudo crear el grupo', mintFailed: 'No se pudo crear el token', revokeTokenTitle: 'Revocar token de registro', revokeTokenMessage: '¿Revocar el token {prefix}…? Los ejecutores ya no podrán registrarse con él.', revokeTokenFailed: 'No se pudo revocar el token', revokeRunnerMessage: '¿Expulsar al ejecutor {name}? Tendrá que registrarse de nuevo.', revokeRunnerFailed: 'No se pudo expulsar al ejecutor', copied: 'Copiado al portapapeles', copyFailed: 'No se pudo copiar; selecciona y copia manualmente',
    },
  } },
  workspaceMembers: {
    invalidWorkspace: 'Espacio de trabajo no válido.', loadFailed: 'No se pudieron cargar los miembros del espacio de trabajo.', addMemberFailed: 'No se pudo añadir el miembro: {error}', addGroupFailed: 'No se pudo añadir el grupo: {error}',
    removeRoleTitle: '¿Quitar el rol {role} a {name}?', removeRoleMessage: 'Se eliminarán la asignación del rol y sus permisos.', removeRoleFailed: 'No se pudo quitar el rol: {error}',
    summaryTitle: 'Resumen de acceso', summaryDescription: 'Muestra cómo se asignan los roles en este espacio. Un rol sin miembros ni grupos asignados está disponible para todos. Jerarquía de permisos: {viewer} → {editor} → {tester}.',
    role: 'Rol', effectiveAccess: 'Acceso', assignments: 'Asignaciones', memberOrGroup: 'Miembro o grupo', rolesLabel: 'Roles', actions: 'Acciones',
    roles: {
      viewer: { name: 'Lector', description: 'Ver el contenido del espacio y participar en conversaciones' },
      editor: { name: 'Editor', description: 'Crear y editar elementos de trabajo en este espacio' },
      tester: { name: 'Tester', description: 'Ver elementos, ejecutar pruebas, gestionar casos de prueba y crear defectos' },
      administrator: { name: 'Administrador', description: 'Gestionar todo el espacio, incluidos los permisos de acceso' },
    },
    memberCount: '{count} miembros', memberCount_one: '{count} miembro', memberCount_other: '{count} miembros', everyone: 'Todos', noDirectAssignments: 'Sin asignaciones directas',
    addMember: 'Añadir miembro', addGroup: 'Añadir grupo', searchPlaceholder: 'Buscar miembros o grupos por nombre o correo…', loading: 'Cargando miembros…', empty: 'Aún no hay miembros ni grupos. Añádelos para configurar el acceso a este espacio.', noSearchResults: 'No se encontraron miembros ni grupos para «{query}».',
    unknownUser: 'Usuario desconocido', group: 'Grupo', removeRoleAction: 'Quitar rol: {role}', addMemberTitle: 'Añadir miembro al espacio', user: 'Usuario', selectUser: 'Selecciona un usuario…', selectRole: 'Selecciona un rol…', addingMember: 'Añadiendo miembro…', cancel: 'Cancelar', addGroupTitle: 'Añadir grupo al espacio', selectGroup: 'Selecciona un grupo…', addingGroup: 'Añadiendo grupo…',
  },
  integrations: {
    directions: { outbound: 'Salientes', inbound: 'Entrantes', outboundDescription: 'Aplicaciones a las que se conecta Windshift. Añade credenciales OAuth para leer datos de servicios externos como Notion o Confluence.', inboundDescription: 'Aplicaciones que se conectan a Windshift en nombre del usuario. Registra una aplicación una vez y los usuarios la autorizan con OAuth 2.0 y PKCE.' },
    providers: { loadFailed: 'No se pudieron cargar los proveedores de integraciones', saveFailed: 'No se pudo guardar el proveedor', deleteMessage: 'Se eliminará el proveedor de integración y se desconectará a todos los usuarios.', deleteFailed: 'No se pudo eliminar el proveedor', namePlaceholder: 'Mi integración con Notion' },
    oauthClients: {
      title: 'Clientes OAuth', subtitle: 'Registra aplicaciones externas que autorizan usuarios de Windshift mediante OAuth 2.0 y PKCE y crean tokens de API por usuario.', empty: 'No hay clientes OAuth registrados', emptyDescription: 'Pulsa Registrar cliente para añadir una aplicación externa.', loadFailed: 'No se pudieron cargar los clientes OAuth', updated: 'Cliente OAuth actualizado', publicCreated: 'Cliente OAuth público creado', saveFailed: 'No se pudo guardar el cliente OAuth', rotateTitle: '¿Reemplazar el secreto de «{name}»?', rotateMessage: 'El secreto anterior dejará de funcionar de inmediato. Los tokens existentes seguirán hasta caducar; los intercambios futuros con el secreto anterior fallarán.', rotateFailed: 'No se pudo reemplazar el secreto', deleteMessage: 'Todos los tokens de acceso y actualización de este cliente se revocarán de inmediato. Los usuarios deberán volver a conectarse.', deleted: 'Cliente OAuth eliminado', deleteFailed: 'No se pudo eliminar el cliente OAuth', scopeHelp: 'Los tokens emitidos son tokens de API de Windshift por usuario. Heredan sus permisos, limitados a los ámbitos seleccionados.', redirectCount: 'URI de redirección: {count}', rotateSecret: 'Reemplazar secreto del cliente', editTitle: 'Editar cliente OAuth', registerTitle: 'Registrar cliente OAuth', confidential: 'Confidencial (servidor a servidor, con secreto)', public: 'Público (solo PKCE, sin secreto)', clientTypeHelp: 'Los clientes confidenciales guardan client_secret en el servidor. Los públicos deben usar PKCE en cada intercambio de tokens.', redirectHelp: 'Introduce una URI por línea. redirect_uri debe coincidir exactamente con una de ellas.', copySecretNow: 'Copia ahora este secreto', secretWarning: 'El secreto del cliente solo se muestra una vez. Windshift guarda únicamente su hash bcrypt; cópialo antes de cerrar. Si se pierde, reemplázalo.',
    },
  },
  systemCatalog: {
    statuses: { open: 'Abierto', inProgress: 'En curso', done: 'Hecho' },
    statusCategories: { toDo: 'Por hacer', inProgress: 'En curso', done: 'Hecho' },
  },
});
