import { withEnglishAdminOperations } from '../adminOperationsFallback.js';

export default withEnglishAdminOperations({
  settings: { adminOperations: {
    tabs: { capabilities: 'الإمكانات', credentials: 'بيانات الاعتماد', runnerPools: 'مجموعات المشغّلات' },
    agentTemplates: {
      title: 'قوالب الوكلاء', subtitle: 'تجاوز كتالوج Agent Studio: أسماء القوالب وأنواع الملفات والتعليمات', addTemplate: 'إضافة قالب', empty: 'لا توجد تجاوزات مهيأة بعد. يستخدم Agent Studio الإعدادات الافتراضية المضمنة.', startFromNew: 'البدء من الصفر (قالب مخصص جديد)', loadFailed: 'تعذر تحميل قوالب الوكلاء: {error}', templateKeyRequired: 'مفتاح القالب مطلوب', nameRequired: 'الاسم مطلوب', saveFailed: 'تعذر الحفظ: {error}', deleteMessage: 'هل تريد حذف تجاوز «{name}»؟ سيؤدي ذلك إلى استعادة القالب الافتراضي.', editOverride: 'تحرير تجاوز القالب', addOverride: 'إضافة تجاوز للقالب', startFromDefault: 'البدء من قالب افتراضي', startFromPlaceholder: 'تجاوز قالب مضمن أو إنشاء قالب جديد', startFromHelp: 'سيتم استبدال القالب المحدد بتعديلاتك؛ ينشئ خيار البدء من الصفر قالباً جديداً.', builtInOverride: 'يستبدل هذا التجاوز القالب المضمن «{name}».', namePlaceholder: 'مثال: مهندس برمجيات', instructionsPlaceholder: 'موجّه النظام أو الدور الخاص بهذا القالب',
    },
    llmConnections: {
      title: 'اتصالات الذكاء الاصطناعي', subtitle: 'تهيئة مزودي نماذج الذكاء الاصطناعي للميزات الذكية', addConnection: 'إضافة اتصال', empty: 'لم تتم تهيئة اتصالات ذكاء اصطناعي بعد.', addFirst: 'إضافة الاتصال الأول', referenced: 'مستخدم بواسطة إمكانات مفعّلة', visionTitle: 'يمكن لهذا النموذج تحليل الصور في عناصر العمل', noVisionTitle: 'هذا النموذج نصي فقط ولا يمكنه رؤية الصور', addTitle: 'إضافة اتصال ذكاء اصطناعي', editTitle: 'تحرير اتصال الذكاء الاصطناعي', disableWarning: 'سيؤدي تعطيل هذا الاتصال إلى إيقاف إمكانات إجراءات LLM التابعة أثناء التشغيل.', disableWarningHelp: 'مستخدم بواسطة {capabilities}. ستظل الإمكانات ظاهرة كمفعلة لكنها ستفشل حتى إعادة تمكين الاتصال أو تغييره.', namePlaceholder: 'مثال: OpenRouter Claude Sonnet', selectProvider: 'اختر مزوداً…', keyConfigured: 'المفتاح مهيأ (اتركه فارغاً للاحتفاظ به)', enterApiKey: 'أدخل مفتاح API', searchModels: 'ابحث عن النماذج أو أدخل معرّفاً…', typeModelId: 'أدخل معرّف النموذج أو اضغط تحديث', supportsImages: 'يدعم إدخال الصور', lastAttemptFailed: 'فشلت المحاولة الأخيرة: {error}', enterBaseUrlHelp: 'أدخل عنوان URL أساسياً لجلب النماذج أو أدخل معرّف النموذج يدوياً.', noCachedModels: 'لا توجد نماذج مخزنة مؤقتاً. اضغط تحديث للجلب من {provider} أو أدخل معرّفاً يدوياً.', selectModel: 'اختر نموذجاً…', providerConfig: 'تهيئة المزود (JSON)', providerConfigHelp: 'تُدمج الحقول الاختيارية العليا في طلبات المزود، مع أولوية حقول Windshift الحالية.', visionAuto: 'تلقائي (اكتشاف من النموذج)', visionOn: 'تشغيل (فرض الصور)', visionOff: 'إيقاف (فرض النص فقط)', visionHelp: 'يتحكم في إمكانية إرسال وكيل البرمجة الصور إلى النموذج. يستخدم الوضع التلقائي القدرة المعروفة ويمكن تجاوزه للنماذج المحلية أو المخصصة.', rateHint: '{prompt}/{completion} لكل مليون رمز', refreshedNow: 'تم التحديث للتو', refreshedMinutes: 'تم التحديث قبل {count} دقيقة', refreshedHours: 'تم التحديث قبل {count} ساعة', refreshedDays: 'تم التحديث قبل {count} يوم', modelsFetched: 'تم جلب {count} نموذجاً من {provider}', refreshFailed: 'تعذر تحديث النماذج', loadFailed: 'تعذر تحميل اتصالات الذكاء الاصطناعي', oneCapability: 'إمكانية إجراء مفعلة واحدة: {name}', manyCapabilities: '{count} من إمكانات الإجراءات المفعلة: {names}', deleteTitle: 'حذف اتصال الذكاء الاصطناعي', deleteMessage: 'هل تريد حذف {name}؟ لا يمكن التراجع عن هذا الإجراء.', deleteImpact: 'هذا الاتصال مستخدم بواسطة {capabilities}. ستتوقف هذه الإمكانات عن العمل.', deleted: 'تم حذف اتصال الذكاء الاصطناعي', deleteFailed: 'تعذر حذف الاتصال', configObject: 'يجب أن تكون تهيئة المزود كائن JSON', configJson: 'يجب أن تحتوي تهيئة المزود على JSON صالح', created: 'تم إنشاء اتصال الذكاء الاصطناعي', createFailed: 'تعذر إنشاء الاتصال', updated: 'تم تحديث اتصال الذكاء الاصطناعي', updateFailed: 'تعذر تحديث الاتصال', testPassed: 'نجح اختبار الاتصال', testFailed: 'فشل اختبار الاتصال',
    },
    actionCapabilities: { availableAll: 'متاح في جميع مساحات العمل', availableAllHelp: 'يمكن لإجراءات أي مساحة عمل استخدام هذه الإمكانية.', restrict: 'تقييد بمساحات عمل محددة', restrictHelp: 'يمكن فقط للمساحات المحددة أدناه استخدام هذه الإمكانية.', noWorkspaces: 'لا توجد مساحات عمل متاحة.', useCredential: 'استخدام بيانات اعتماد للمصادقة', globalCredentialHelp: 'يمكن للإمكانات العامة استخدام بيانات الاعتماد العامة فقط.', workspaceCredentialHelp: 'يمكن لإمكانات مساحة العمل استخدام بيانات عامة أو مسموحاً بها لتلك المساحة.', scheme: 'المخطط (لرموز Bearer فقط)', additionalHeaders: 'ترويسات سرية إضافية', addSecretHeader: 'إضافة ترويسة سرية', additionalHeadersHelp: 'لواجهات API التي تحتاج إلى عدة ترويسات سرية. يتم حل بيانات كل صف وقت الطلب.', defaultHeadersHelp: 'ترويسات غير حساسة فقط. توضع رموز المصادقة في القسم أدناه.' },
    actionCredentials: { title: 'بيانات اعتماد الإجراءات', subtitle: 'رموز API مشفرة لإمكانات HTTP. القيم السرية للكتابة فقط ولا يمكن قراءتها بعد الحفظ.', add: 'إضافة بيانات اعتماد', addFirst: 'إضافة بيانات الاعتماد الأولى', empty: 'لا توجد بيانات اعتماد بعد.', basicAuth: 'مصادقة أساسية (مستخدم:كلمة مرور)', customHeader: 'قيمة ترويسة مخصصة', loadFailed: 'تعذر تحميل بيانات اعتماد الإجراءات', nameSecretRequired: 'الاسم والقيمة السرية مطلوبان', workspaceRequired: 'اختر مساحة عمل واحدة على الأقل أو اسمح لجميع المساحات.', created: 'تم إنشاء بيانات الاعتماد ({prefix})', createFailed: 'تعذر إنشاء بيانات الاعتماد', updateFailed: 'تعذر تحديث بيانات الاعتماد', rotated: 'تم استبدال القيمة السرية ({prefix})', rotateFailed: 'تعذر استبدال القيمة السرية', deleteMessage: 'هل تريد حذف {name}؟ ستفشل الإمكانات التي ما زالت تستخدمها أثناء التشغيل.', deleteFailed: 'تعذر حذف بيانات الاعتماد', storedSecret: 'محفوظ ولا يُعرض كاملاً أبداً', availableAll: 'متاح في جميع مساحات العمل', availableAllHelp: 'يمكن لأي مساحة عمل استخدام بيانات الاعتماد هذه.', restrict: 'تقييد بمساحات عمل محددة', restrictHelp: 'يمكن فقط للمساحات المحددة أدناه استخدام بيانات الاعتماد هذه.', noWorkspaces: 'لا توجد مساحات عمل متاحة.', secretPlaceholder: 'أدخل رمزاً أو مفتاح API أو مستخدم:كلمة مرور', secretHelp: 'يُحفظ مشفراً ولن يظهر مرة أخرى، ويمكن استبداله عند الحاجة.', metadata: 'بيانات وصفية (JSON، اختيارية)', metadataHelp: 'بيانات غير حساسة فقط. تُرفض مفاتيح مثل token وsecret وpassword.', storedRotate: 'محفوظ ({prefix}) — استخدم الاستبدال لتعيين قيمة جديدة.', rotateTitle: 'استبدال القيمة السرية — {name}', rotateHelp: 'أدخل القيمة السرية الجديدة. ستُستبدل القديمة فوراً ولا يمكن استعادتها.' },
    runnerPools: { title: 'مجموعات المشغّلات', subtitle: 'مجموعات مشغّلات بعيدة لتنفيذ مهام وكيل البرمجة. أنشئ رمز تسجيل لإضافة مضيف مشغّل.', empty: 'لا توجد مجموعات مشغّلات', emptyDescription: 'أنشئ مجموعة ثم رمز تسجيل لتوصيل مضيف مشغّل.', registrationTokens: 'رموز التسجيل — {name}', noTokens: 'لا توجد رموز بعد', runnersForPool: 'المشغّلات — {name}', noRunners: 'لا توجد مشغّلات مسجلة', newPoolTitle: 'مجموعة مشغّلات جديدة', maxConcurrentRuns: 'الحد الأقصى للتشغيلات المتزامنة', zeroUnlimited: '0 = غير محدود', availableAll: 'متاح لجميع مساحات العمل', mintTitle: 'إنشاء رمز تسجيل', expiresHours: 'تنتهي الصلاحية خلال (ساعات)', zeroNeverExpires: '0 = لا تنتهي صلاحيته (ألغِه لتعطيله)', addHostTitle: 'إضافة مضيف المشغّل', installHelp: 'نفّذ هذا على المضيف. سيتم تثبيت حاوية المشغّل وتشغيلها بعنوان الخادم ووسم الصورة المطابق والرمز الجديد.', manualPrefix: 'هل تفضّل الإعداد اليدوي؟ عيّن الرمز كـ', setTokenPrefix: 'عيّن الرمز كـ', tokenOnce: 'على مضيف المشغّل. يظهر مرة واحدة ولا يمكن استعادته لاحقاً.', loadFailed: 'تعذر تحميل مجموعات المشغّلات', tokensLoadFailed: 'تعذر تحميل الرموز', runnersLoadFailed: 'تعذر تحميل المشغّلات', created: 'تم إنشاء مجموعة المشغّلات', createFailed: 'تعذر إنشاء المجموعة', mintFailed: 'تعذر إنشاء الرمز', revokeTokenTitle: 'إلغاء رمز التسجيل', revokeTokenMessage: 'هل تريد إلغاء الرمز {prefix}…؟ لن تتمكن المشغّلات من التسجيل به.', revokeTokenFailed: 'تعذر إلغاء الرمز', revokeRunnerMessage: 'هل تريد إخراج المشغّل {name}؟ يجب تسجيله مجدداً للانضمام.', revokeRunnerFailed: 'تعذر إخراج المشغّل', copied: 'تم النسخ إلى الحافظة', copyFailed: 'فشل النسخ — حدّد النص وانسخه يدوياً' },
  } },
  workspaceMembers: {
    invalidWorkspace: 'مساحة العمل غير صالحة.', loadFailed: 'تعذر تحميل أعضاء مساحة العمل.', addMemberFailed: 'تعذرت إضافة العضو: {error}', addGroupFailed: 'تعذرت إضافة المجموعة: {error}',
    removeRoleTitle: 'إزالة دور {role} من {name}؟', removeRoleMessage: 'سيؤدي ذلك إلى إزالة تعيين الدور وصلاحياته.', removeRoleFailed: 'تعذرت إزالة الدور: {error}',
    summaryTitle: 'ملخص الوصول', summaryDescription: 'يعرض كيفية تعيين الأدوار في مساحة العمل. يكون الدور بلا أعضاء أو مجموعات معينة متاحاً للجميع. تسلسل الصلاحيات: {viewer} ← {editor} ← {tester}.',
    role: 'الدور', effectiveAccess: 'الوصول', assignments: 'التعيينات', memberOrGroup: 'عضو أو مجموعة', rolesLabel: 'الأدوار', actions: 'الإجراءات',
    roles: {
      viewer: { name: 'مشاهد', description: 'عرض محتوى مساحة العمل والمشاركة في المناقشات' },
      editor: { name: 'محرر', description: 'إنشاء عناصر العمل وتحريرها في هذه المساحة' },
      tester: { name: 'مختبر', description: 'عرض العناصر وتشغيل الاختبارات وإدارة حالات الاختبار وإنشاء العيوب' },
      administrator: { name: 'مسؤول', description: 'إدارة مساحة العمل بالكامل بما فيها صلاحيات الوصول' },
    },
    memberCount: '{count} أعضاء', memberCount_one: '{count} عضو', memberCount_other: '{count} أعضاء', everyone: 'الجميع', noDirectAssignments: 'لا توجد تعيينات مباشرة',
    addMember: 'إضافة عضو', addGroup: 'إضافة مجموعة', searchPlaceholder: 'البحث عن أعضاء أو مجموعات بالاسم أو البريد…', loading: 'جارٍ تحميل الأعضاء…', empty: 'لا يوجد أعضاء أو مجموعات بعد. أضفهم لتهيئة الوصول إلى مساحة العمل.', noSearchResults: 'لم يتم العثور على أعضاء أو مجموعات لعبارة «{query}».',
    unknownUser: 'مستخدم غير معروف', group: 'مجموعة', removeRoleAction: 'إزالة الدور: {role}', addMemberTitle: 'إضافة عضو إلى مساحة العمل', user: 'المستخدم', selectUser: 'اختر مستخدماً…', selectRole: 'اختر دوراً…', addingMember: 'جارٍ إضافة العضو…', cancel: 'إلغاء', addGroupTitle: 'إضافة مجموعة إلى مساحة العمل', selectGroup: 'اختر مجموعة…', addingGroup: 'جارٍ إضافة المجموعة…',
  },
  integrations: {
    directions: { outbound: 'صادرة', inbound: 'واردة', outboundDescription: 'التطبيقات التي يتصل بها Windshift. أضف بيانات OAuth لقراءة بيانات من خدمات خارجية مثل Notion أو Confluence.', inboundDescription: 'التطبيقات التي تتصل بـ Windshift نيابة عن المستخدم. سجّل التطبيق مرة واحدة ثم يفوضه المستخدمون عبر OAuth 2.0 وPKCE.' },
    providers: { loadFailed: 'تعذر تحميل مزودي التكامل', saveFailed: 'تعذر حفظ المزود', deleteMessage: 'سيؤدي ذلك إلى إزالة مزود التكامل وفصل جميع المستخدمين.', deleteFailed: 'تعذر حذف المزود', namePlaceholder: 'تكامل Notion الخاص بي' },
    oauthClients: { title: 'عملاء OAuth', subtitle: 'سجّل تطبيقات خارجية تفوض مستخدمي Windshift عبر OAuth 2.0 وPKCE وتنشئ رموز API لكل مستخدم.', empty: 'لا يوجد عملاء OAuth مسجلون', emptyDescription: 'اضغط تسجيل عميل لإضافة تطبيق خارجي.', loadFailed: 'تعذر تحميل عملاء OAuth', updated: 'تم تحديث عميل OAuth', publicCreated: 'تم إنشاء عميل OAuth عام', saveFailed: 'تعذر حفظ عميل OAuth', rotateTitle: 'استبدال سر «{name}»؟', rotateMessage: 'سيتوقف السر السابق فوراً. تستمر الرموز الحالية حتى انتهاء صلاحيتها، وستفشل عمليات التبادل الجديدة باستخدام السر القديم.', rotateFailed: 'تعذر استبدال السر', deleteMessage: 'ستُلغى فوراً جميع رموز الوصول والتحديث الصادرة لهذا العميل. سيحتاج المستخدمون إلى إعادة الاتصال.', deleted: 'تم حذف عميل OAuth', deleteFailed: 'تعذر حذف عميل OAuth', scopeHelp: 'الرموز الصادرة هي رموز Windshift API لكل مستخدم. ترث أذونات المستخدم ضمن النطاقات المحددة.', redirectCount: 'عناوين إعادة التوجيه: {count}', rotateSecret: 'استبدال سر العميل', editTitle: 'تحرير عميل OAuth', registerTitle: 'تسجيل عميل OAuth', confidential: 'سري (خادم إلى خادم، مع سر)', public: 'عام (PKCE فقط، بلا سر)', clientTypeHelp: 'يخزن العميل السري client_secret على الخادم. يجب على العميل العام استخدام PKCE في كل تبادل للرموز.', redirectHelp: 'أدخل عنواناً واحداً في كل سطر. يجب أن يطابق redirect_uri أحدها تماماً.', copySecretNow: 'انسخ هذا السر الآن', secretWarning: 'يظهر سر العميل مرة واحدة فقط. يخزن Windshift تجزئة bcrypt فقط؛ انسخه قبل إغلاق النافذة واستبدله إذا فُقد.' },
  },
  systemCatalog: {
    statuses: { open: 'مفتوح', inProgress: 'قيد التنفيذ', done: 'مكتمل' },
    statusCategories: { toDo: 'للتنفيذ', inProgress: 'قيد التنفيذ', done: 'مكتمل' },
  },
});
